--创建序列
create sequence SEQ_GCC_ID
minvalue 1
maxvalue 9999999999999999999999999999999999
start with 10000
increment by 1
cache 20;


ALTER TABLE CONFIG
 DROP PRIMARY KEY CASCADE;
DROP TABLE CONFIG CASCADE CONSTRAINTS;

CREATE TABLE CONFIG
(
  ID                NUMBER,
  PROFILEID         NUMBER,
  KEY               VARCHAR2(255 BYTE),
  VALUE             VARCHAR2(4000),
  LASTVERSIONVALUE VARCHAR2(4000),
  DESCRIPTION       VARCHAR2(255 BYTE),
  CREATETIME        DATE,
  UPDATETIME        DATE,
  CREATEUSER        VARCHAR2(255 BYTE),
  UPDATEUSER        VARCHAR2(255 BYTE),
  VERSION           NUMBER
);


ALTER TABLE DEPENDENCY
 DROP PRIMARY KEY CASCADE;
DROP TABLE DEPENDENCY CASCADE CONSTRAINTS;

CREATE TABLE DEPENDENCY
(
  ID                   NUMBER,
  PROJECTID            NUMBER,
  DEPENDENCYPROJECTID  NUMBER
);


ALTER TABLE GROUP_ROLES
 DROP PRIMARY KEY CASCADE;
DROP TABLE GROUP_ROLES CASCADE CONSTRAINTS;

CREATE TABLE GROUP_ROLES
(
  GROUPID  NUMBER,
  ROLEID   NUMBER
);


ALTER TABLE PERMISSION
 DROP PRIMARY KEY CASCADE;
DROP TABLE PERMISSION CASCADE CONSTRAINTS;

CREATE TABLE PERMISSION
(
  ID             NUMBER,
  PERMISSIONSTR  VARCHAR2(255 BYTE),
  DESCRIPTION    VARCHAR2(255 BYTE)
);


ALTER TABLE PROFILE
 DROP PRIMARY KEY CASCADE;
DROP TABLE PROFILE CASCADE CONSTRAINTS;

CREATE TABLE PROFILE
(
  ID           NUMBER,
  PROJECTID    NUMBER,
  NAME         VARCHAR2(255 BYTE),
  ACCESSES     NUMBER,
  SECRETKEY    VARCHAR2(255 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE),
  CREATETIME   DATE,
  UPDATEDATE   DATE
);


ALTER TABLE PROJECT
 DROP PRIMARY KEY CASCADE;
DROP TABLE PROJECT CASCADE CONSTRAINTS;

CREATE TABLE PROJECT
(
  ID                NUMBER,
  GROUPID           VARCHAR2(255 BYTE),
  ARTIFACTID        VARCHAR2(255 BYTE),
  VERSION           VARCHAR2(255 BYTE),
  OWNERGROUP        NUMBER,
  DESCRIPTION       VARCHAR2(255 BYTE),
  BPUBLIC           NUMBER,
  BALLOWDEPENDENCY  NUMBER
);


ALTER TABLE ROLE
 DROP PRIMARY KEY CASCADE;
DROP TABLE ROLE CASCADE CONSTRAINTS;

CREATE TABLE ROLE
(
  ID           NUMBER,
  NAME         VARCHAR2(255 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE)
);


ALTER TABLE ROLE_PERMISSIONS
 DROP PRIMARY KEY CASCADE;
DROP TABLE ROLE_PERMISSIONS CASCADE CONSTRAINTS;

CREATE TABLE ROLE_PERMISSIONS
(
  ROLEID        NUMBER,
  PERMISSIONID  NUMBER
);


ALTER TABLE USER_GROUPS
 DROP PRIMARY KEY CASCADE;
DROP TABLE USER_GROUPS CASCADE CONSTRAINTS;

CREATE TABLE USER_GROUPS
(
  USERID    NUMBER,
  GROUPID   NUMBER,
  ACCESSES  NUMBER
);


ALTER TABLE USER_ROLES
 DROP PRIMARY KEY CASCADE;
DROP TABLE USER_ROLES CASCADE CONSTRAINTS;

CREATE TABLE USER_ROLES
(
  USERID  NUMBER,
  ROLEID  NUMBER
);


ALTER TABLE XGROUP
 DROP PRIMARY KEY CASCADE;
DROP TABLE XGROUP CASCADE CONSTRAINTS;

CREATE TABLE XGROUP
(
  ID           NUMBER,
  NAME         VARCHAR2(255 BYTE)               NOT NULL,
  DESCRIPTION  VARCHAR2(255 BYTE)               DEFAULT NULL
);


ALTER TABLE XUSER
 DROP PRIMARY KEY CASCADE;
DROP TABLE XUSER CASCADE CONSTRAINTS;

CREATE TABLE XUSER
(
  ID             NUMBER,
  NAME           VARCHAR2(255 BYTE),
  NICKNAME       VARCHAR2(255 BYTE),
  PASSWORD       VARCHAR2(255 BYTE),
  PASSWORDSALT   VARCHAR2(255 BYTE),
  EMAIL          VARCHAR2(255 BYTE),
  CREATETIME     DATE,
  UPDATETIME     DATE,
  LASTLOGINTIME  DATE,
  LOGINCOUNT     NUMBER,
  PROVIDER       VARCHAR2(255 BYTE)
);


CREATE UNIQUE INDEX GROUPNAME ON XGROUP(NAME);


CREATE INDEX IDX_GROUPID_ARTIFACTID_VERSION ON PROJECT(GROUPID, ARTIFACTID, VERSION);


CREATE INDEX IDX_PERMISSIONPERMISSION ON PERMISSION(PERMISSIONSTR);


CREATE INDEX IDX_PROFILEID_KEYCONFIG ON CONFIG(PROFILEID, KEY);


CREATE INDEX IDX_PROJECTID_DEPENDENCYPROJEC ON DEPENDENCY(PROJECTID, DEPENDENCYPROJECTID);


CREATE INDEX IDX_PROJECTID_PROFILENAMEPROFI ON PROFILE(PROJECTID, NAME);


CREATE INDEX IDX_ROLE_NAMEROLE ON ROLE(NAME);


CREATE UNIQUE INDEX PRIMARYCONFIG1 ON CONFIG(ID);


CREATE UNIQUE INDEX PRIMARYDEPENDENCY1 ON DEPENDENCY(ID);


CREATE UNIQUE INDEX PRIMARYGROUP_ROLES1 ON GROUP_ROLES(GROUPID, ROLEID);


CREATE UNIQUE INDEX PRIMARYPERMISSION1 ON PERMISSION(ID);


CREATE UNIQUE INDEX PRIMARYPROFILE1 ON PROFILE(ID);


CREATE UNIQUE INDEX PRIMARYPROJECT1 ON PROJECT(ID);


CREATE UNIQUE INDEX PRIMARYROLE1 ON ROLE(ID);


CREATE UNIQUE INDEX PRIMARYROLE_PERMISSIONS1 ON ROLE_PERMISSIONS(ROLEID, PERMISSIONID);


CREATE UNIQUE INDEX PRIMARYUSER_GROUPS1 ON USER_GROUPS(USERID, GROUPID);


CREATE UNIQUE INDEX PRIMARYUSER_ROLES1 ON USER_ROLES(USERID, ROLEID);


ALTER TABLE CONFIG ADD (
  CONSTRAINT PRIMARYCONFIG1
 PRIMARY KEY
 (ID);

ALTER TABLE DEPENDENCY ADD
  CONSTRAINT PRIMARYDEPENDENCY1
 PRIMARY KEY
 (ID);

ALTER TABLE GROUP_ROLES ADD
  CONSTRAINT PRIMARYGROUP_ROLES1
 PRIMARY KEY
 (GROUPID, ROLEID);

ALTER TABLE PERMISSION ADD
  CONSTRAINT PRIMARYPERMISSION1
 PRIMARY KEY
 (ID);

ALTER TABLE PROFILE ADD
  CONSTRAINT PRIMARYPROFILE1
 PRIMARY KEY
 (ID);

ALTER TABLE PROJECT ADD
  CONSTRAINT PRIMARYPROJECT1
 PRIMARY KEY
 (ID);

ALTER TABLE ROLE ADD
  CONSTRAINT PRIMARYROLE1
 PRIMARY KEY
 (ID);

ALTER TABLE ROLE_PERMISSIONS ADD
  CONSTRAINT PRIMARYROLE_PERMISSIONS1
 PRIMARY KEY
 (ROLEID, PERMISSIONID);

ALTER TABLE USER_GROUPS ADD
  CONSTRAINT PRIMARYUSER_GROUPS1
 PRIMARY KEY
 (USERID, GROUPID);

ALTER TABLE USER_ROLES ADD
  CONSTRAINT PRIMARYUSER_ROLES1
 PRIMARY KEY
 (USERID, ROLEID);

ALTER TABLE XGROUP ADD
  PRIMARY KEY
 (ID);

ALTER TABLE XUSER ADD
  PRIMARY KEY
 (ID);